[server]
# Aumentar límite de carga de archivos a 300MB
maxUploadSize = 300

# Configuración del servidor
port = 8503
address = "0.0.0.0"

# Configuración de la aplicación
headless = false
runOnSave = true

[browser]
# Configuración del navegador
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8503

[theme]
# Tema personalizado
primaryColor = "#5CE488"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
# Configuración del cliente
showErrorDetails = true
toolbarMode = "auto"